[package]
name = "betterdisplay-input-switcher"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
toml = "0.9.5"

[[bin]]
name = "betterdisplay-input-switcher"
path = "main.rs"
