[package]
name = "betterdisplay-kvm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
env_logger = "0.11.8"
futures-lite = "2.0"
log = "0.4.27"
nusb = "0.2.0"

[[bin]]
name = "betterdisplay-kvm"
path = "main.rs"
