# USB Device Monitor Configuration
# 
# This file contains the configuration for monitoring USB devices
# and automatically switching BetterDisplay inputs when devices connect/disconnect

# USB Device Information
vendor_id = "046d"
device_id = "c547"

# BetterDisplay DDC Commands
disconnect_ddc = "18"     # DDC value to use when device disconnects
connect_ddc = "15"        # DDC value to use when device connects

# Example configurations for common devices:
# 
# Apple Magic Keyboard:
# vendor_id = "05ac"
# device_id = "026c"
# 
# Logitech MX Master:
# vendor_id = "046d"
# device_id = "c52b"
# 
# Microsoft Surface Dock:
# vendor_id = "045e"
# device_id = "090a"
