name: "CI"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  cargo-fmt:
    name: Format
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust stable
        if: steps.changes.outputs.desktop == 'true'
        uses: dtolnay/rust-toolchain@stable
        with:
          target: "${{ matrix.settings.toolchain }}"
      - uses: Swatinem/rust-cache@v2
        if: steps.changes.outputs.desktop == 'true'
        with:
          workspaces: "apps/desktop/src-tauri/target"
      - name: Cargo format
        if: steps.changes.outputs.desktop == 'true'
        run: cargo fmt --check
        working-directory: apps/desktop/src-tauri

  build:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          target: "${{ matrix.settings.toolchain }}"
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
