name: "CI"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  cargo-fmt:
    name: Format
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          target: "${{ matrix.settings.toolchain }}"
      - uses: Swatinem/rust-cache@v2
      - name: Cargo format
        run: cargo fmt --check

  build:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          target: aarch64-apple-darwin,x86_64-apple-darwin
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
